version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - media_volume:/usr/src/backend/media

  web:
    build: ./backend  # Path to the Dockerfile inside the `backend` folder
    command: sh -c "python manage.py migrate && gunicorn django_backend.wsgi:application --bind 0.0.0.0:8010"  # Run migrations before starting the server
    volumes:
      - ./backend:/usr/src/backend  # Mount the `backend` directory to `/usr/src/backend` in the container
      - media_volume:/usr/src/backend/media
    expose:
      - 8010  # Expose port 8010 for internal container communication
    env_file:
      - ./.env  # Use the environment variables from `.env` in the project root
    depends_on:
      - db
      - daphne

  daphne:
    build: ./backend
    command: daphne --bind 0.0.0.0 -p 8002 django_backend.asgi:application
    ports:
      - 8002:8002

  db:
    image: postgres:15
    volumes:
      - /postgres_data/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=djangodb

volumes:
  postgres_data:
  media_volume:
