version: '3.8'

services:
  nginx: 
    build: ./nginx
    ports:
     - 1337:80
    depends_on:
      - web
  web:
    build: ./backend  # Path to the Dockerfile inside the `backend` folder
    command: gunicorn django_backend.wsgi:application --bind 0.0.0.0:8010  # Run the server on 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/backend  # Mount the `backend` directory to `/usr/src/backend` in the container
    expose:
      - 8010  # Map port 8000 on the host to port 8000 in the container
    env_file:
      - ./.env  # Use the environment variables from `.env` in the project root
    depends_on:
      - db
      - daphne
  daphne:
    build: ./django_backend
    command: daphne --bind 0.0.0.0 -p 8002 django_backend.asgi:application
    ports:
      - 8002:8002

  db:
    image: postgres:15
    volumes:
      - /postgres_data/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=djangodb
  
volumes:
  postgres_data:
