# Generated by Django 5.1.3 on 2024-11-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_reservation_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_nights',
            field=models.IntegerField(editable=False),
        ),
    ]
