# Generated by Django 5.1.3 on 2024-11-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_reservation_number_of_nights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_nights',
            field=models.IntegerField(),
        ),
    ]
