# Generated by Django 5.1.3 on 2024-11-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_reservation_number_of_nights'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.IntegerField(default=1),
        ),
    ]
